# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1500)),
            ],
            options={
                'db_table': 'about',
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('\u0416\u0435\u043b\u0442\u0430\u044f', '\u0416\u0435\u043b\u0442\u0430\u044f'), ('\u041a\u0440\u0430\u0441\u043d\u0430\u044f', '\u041a\u0440\u0430\u0441\u043d\u0430\u044f')], max_length=20)),
            ],
            options={
                'db_table': 'cards',
                'verbose_name': 'Card',
                'verbose_name_plural': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'championship',
                'verbose_name': 'Championship',
                'verbose_name_plural': 'Championship',
            },
        ),
        migrations.CreateModel(
            name='ClubPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('position', models.CharField(choices=[('\u0412\u0440\u0430\u0442\u0430\u0440\u044c', '\u0412\u0440\u0430\u0442\u0430\u0440\u044c'), ('\u0417\u0430\u0449\u0438\u0442\u043d\u0438\u043a', '\u0417\u0430\u0449\u0438\u0442\u043d\u0438\u043a'), ('\u041f\u043e\u043b\u0443\u0437\u0430\u0449\u0438\u0442\u043d\u0438\u043a', '\u041f\u043e\u043b\u0443\u0437\u0430\u0449\u0438\u0442\u043d\u0438\u043a'), ('\u041d\u0430\u043f\u0430\u0434\u0430\u044e\u0449\u0438\u0439', '\u041d\u0430\u043f\u0430\u0434\u0430\u044e\u0449\u0438\u0439')], max_length=20)),
                ('number', models.IntegerField()),
                ('start_a_career_in_this_club', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_of_a_career_in_this_club', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'club_players',
                'verbose_name': 'Club Players',
                'verbose_name_plural': 'Club Players',
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_time', models.IntegerField()),
                ('own_goal', models.BooleanField()),
                ('penalties', models.BooleanField()),
            ],
            options={
                'db_table': 'goals',
                'verbose_name': 'Goals',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.IntegerField()),
                ('host', models.CharField(max_length=50)),
                ('guests', models.CharField(max_length=50)),
                ('date_of_the_match', models.DateTimeField()),
                ('main_judge', models.CharField(max_length=50)),
                ('first_assistant_of_sud', models.CharField(max_length=50)),
                ('second_assistant_of_sud', models.CharField(max_length=50)),
                ('delegate_of_the_match', models.CharField(max_length=50)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Championship')),
            ],
            options={
                'db_table': 'match',
                'verbose_name': 'Match',
                'verbose_name_plural': 'Match',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u041d\u043e\u0432\u043e\u0441\u0442\u0438')),
                ('image', models.ImageField(upload_to=b'')),
                ('tags', models.CharField(max_length=50)),
                ('description_short', models.TextField()),
                ('description_full', models.TextField()),
                ('date_posting', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_editing', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField()),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'news',
                'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0439')),
            ],
            options={
                'db_table': 'news_category',
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043d\u043e\u0432\u043e\u0441\u0442\u0435\u0439',
                'verbose_name_plural': 'news_category',
            },
        ),
        migrations.CreateModel(
            name='PartnersBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to=b'')),
            ],
            options={
                'db_table': 'partners_banner',
                'verbose_name': 'Partners Banner',
                'verbose_name_plural': 'Partners Banner',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('full_name', models.CharField(max_length=50)),
                ('date_born', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('growth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heft', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'players',
                'verbose_name': 'Players',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_of_the_season', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_of_season', models.DateTimeField(default=django.utils.timezone.now)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Championship')),
            ],
            options={
                'db_table': 'season',
                'verbose_name': 'Season',
                'verbose_name_plural': 'Season',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=b'')),
                ('founded', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('vk', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teams',
                'verbose_name': 'Teams',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0439')),
            ],
            options={
                'db_table': 'video_category',
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0432\u0438\u0434\u0435\u043e',
                'verbose_name_plural': 'Video Category',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('description_short', models.TextField()),
                ('date_posting', models.DateTimeField()),
                ('date_editing', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField()),
                ('author', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.VideoCategory')),
            ],
            options={
                'db_table': 'videos',
                'verbose_name': 'Videos',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='club_members',
            field=models.ManyToManyField(blank=True, to='football.Teams'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.NewsCategory', verbose_name='\u0412\u044b\u0431\u0438\u0440\u0438\u0442\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e'),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Season'),
        ),
        migrations.AddField(
            model_name='goals',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Match'),
        ),
        migrations.AddField(
            model_name='goals',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Players'),
        ),
        migrations.AddField(
            model_name='clubplayers',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Teams'),
        ),
        migrations.AddField(
            model_name='clubplayers',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Players'),
        ),
        migrations.AddField(
            model_name='cards',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Match'),
        ),
        migrations.AddField(
            model_name='cards',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.ClubPlayers'),
        ),
    ]
