# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_staff_transferhistoryofstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferhistoryofstaff',
            name='command',
        ),
        migrations.RemoveField(
            model_name='transferhistoryofstaff',
            name='staff',
        ),
        migrations.DeleteModel(
            name='TransferHistoryOfStaff',
        ),
    ]
