# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20170207_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='delegate_of_the_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_of_the_match', to='football.Staff'),
        ),
        migrations.AlterField(
            model_name='match',
            name='first_assistant_of_sud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_assistant_of_sud', to='football.Staff'),
        ),
        migrations.AlterField(
            model_name='match',
            name='main_judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_judge', to='football.Staff'),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_assistant_of_sud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_assistant_of_sud', to='football.Staff'),
        ),
    ]
