# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20170207_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='football.Teams'),
        ),
        migrations.AlterField(
            model_name='match',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='football.Teams'),
        ),
    ]
