# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20170207_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description_full',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_short',
            field=models.TextField(max_length=250),
        ),
    ]
