# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 08:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_auto_20170207_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description_full',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
