# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_auto_20170207_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersbanner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='vk',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
