# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_auto_20170207_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='football.Season'),
            preserve_default=False,
        ),
    ]
