# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_auto_20170207_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ManyToManyField(to='football.Season'),
        ),
    ]
