# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_auto_20170207_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='guests',
        ),
        migrations.AddField(
            model_name='match',
            name='guests',
            field=models.ManyToManyField(related_name='guests', to='football.Teams'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='host',
        ),
        migrations.AddField(
            model_name='match',
            name='host',
            field=models.ManyToManyField(related_name='host', to='football.Teams'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ManyToManyField(to='football.Season'),
        ),
    ]
