# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0025_auto_20170207_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='football.Child')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='football.Family')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(through='football.FamilyChild', to='football.Child'),
        ),
    ]
