# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_auto_20170208_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_child', models.ManyToManyField(to='football.FamilyChild')),
            ],
        ),
    ]
