# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0027_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='familychild',
            name='family_child',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
