# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0028_familychild_family_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familychild',
            name='family_child',
        ),
        migrations.AddField(
            model_name='game',
            name='child',
            field=models.ManyToManyField(related_name='_game_child_+', to='football.Child'),
        ),
        migrations.AddField(
            model_name='game',
            name='family',
            field=models.ManyToManyField(related_name='_game_family_+', to='football.Family'),
        ),
    ]
