# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0029_auto_20170208_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='family',
        ),
        migrations.AddField(
            model_name='game',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Family+', to='football.Family'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='game',
            name='family_child',
        ),
        migrations.AddField(
            model_name='game',
            name='family_child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='football.FamilyChild'),
            preserve_default=False,
        ),
    ]
