# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0030_auto_20170208_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='family',
        ),
    ]
