# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0031_remove_game_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='families',
            field=models.ManyToManyField(through='football.FamilyChild', to='football.Family'),
        ),
    ]
