# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0032_child_families'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familychild',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='football.Child'),
        ),
    ]
