# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0033_auto_20170208_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familychild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='football.Child'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='child',
        ),
        migrations.AddField(
            model_name='game',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FamilyChild.child+', to='football.Child'),
            preserve_default=False,
        ),
    ]
