# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0034_auto_20170208_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.Child'),
        ),
    ]
