# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0035_auto_20170208_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='guests',
        ),
        migrations.AddField(
            model_name='match',
            name='guests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='football.Teams'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='match',
            name='host',
        ),
        migrations.AddField(
            model_name='match',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='football.Teams'),
            preserve_default=False,
        ),
    ]
