# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0036_auto_20170208_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='football.Season'),
            preserve_default=False,
        ),
    ]
