# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0037_auto_20170208_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Artist')),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='families',
        ),
        migrations.RemoveField(
            model_name='family',
            name='children',
        ),
        migrations.RemoveField(
            model_name='familychild',
            name='child',
        ),
        migrations.RemoveField(
            model_name='familychild',
            name='family',
        ),
        migrations.RemoveField(
            model_name='game',
            name='child',
        ),
        migrations.RemoveField(
            model_name='game',
            name='family_child',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='FamilyChild',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Artist'),
        ),
    ]
