# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0039_auto_20170208_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='writer',
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='publication', chained_model_field='publications', default=1, on_delete=django.db.models.deletion.CASCADE, to='football.Writer'),
            preserve_default=False,
        ),
    ]
