# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0041_auto_20170208_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='book',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='publications',
        ),
        migrations.AlterField(
            model_name='match',
            name='guests',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='football.Teams'),
        ),
        migrations.AlterField(
            model_name='match',
            name='host',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='football.Teams'),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='football.Season'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
