# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0046_auto_20170208_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='championship',
        ),
        migrations.AddField(
            model_name='season',
            name='championship',
            field=models.ManyToManyField(to='football.Championship'),
        ),
        migrations.AlterField(
            model_name='season',
            name='club_members',
            field=models.ManyToManyField(blank=True, to='football.Teams'),
        ),
    ]
