# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0048_auto_20170208_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='championship',
            new_name='championships',
        ),
        migrations.AlterField(
            model_name='match',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Championship'),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='championship', chained_model_field='championships', on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='football.Season'),
        ),
    ]
