# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0050_auto_20170208_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guests',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='championships', chained_model_field='season', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='football.Teams'),
        ),
        migrations.AlterField(
            model_name='match',
            name='host',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='championships', chained_model_field='season', on_delete=django.db.models.deletion.CASCADE, related_name='host', to='football.Teams'),
        ),
    ]
