# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0053_auto_20170208_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='championships',
        ),
        migrations.AddField(
            model_name='season',
            name='championships',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='football.Championship'),
            preserve_default=False,
        ),
    ]
