# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0081_auto_20170208_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guests',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='name', chained_model_field='club_members', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='football.Teams'),
        ),
    ]
