# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:55
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0082_auto_20170208_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='club_members',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, to='football.Teams'),
        ),
    ]
